name: statgis
dependencies:
  - python=3.9
  - gdal
  - fiona
  - ipykernel
  - numpy
  - pandas
  - scipy
  - sympy
  - matplotlib
  - jupyter
  - xarray
  - statsmodels
  - pymannkendall
  - tensorflow
  - rasterio
  - shapely
  - pykrige
  - geopandas
  - earthengine-api
  - geemap
  - pip
  - pip:
    - statgis
    - poetry
    - pytest